### ISSUE TITLE
Build method for content type

### ISSUE THREAD

**Issue by moznion** [rjbs/Email-MIME-ContentType#2]
Hello,

When this module had construction method for Content-Type which takes result of `parse_content_type()` as the argument, I thought that it was convenient. 

Like so (Since it wrote promptly, there may be a point that something is not good);
https://gist.github.com/moznion/7496660

Since this processing can be written easily, a user may actually be what to write individually. However, I thought that the way which offered unific processing was good because it doesn't make trifling difference (e.g. treatment of white space, etc...) will not be induced.

**Comment by pali** [comment]
Another problems:
* does not handle space and `tspecials` characters
* does not handle non-ASCII strings
* does not handle long values

**Comment by pali** [comment]
I tried to implement function build_content_type correctly according to RFC 2045 and RFC 2231. Code is in pull request https://github.com/rjbs/Email-MIME-ContentType/pull/11. So please review & test.

**Comment by pali** [comment]
Can somebody review or test my code in pull request? Now it is year since I opened that pull request. Is still somebody interested in it?

**Comment by moznion** [comment]
Thank you so much for this!
